# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n\x11PasswordCheckInfo\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x19\n\x11\x65ncryptedPassword\x18\x02 \x01(\t\"%\n\x08PageInfo\x12\n\n\x02pn\x18\x01 \x01(\r\x12\r\n\x05pSize\x18\x02 \x01(\r\" \n\rCheckResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0cPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"\x1b\n\rUserIDRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"C\n\x0e\x43reateUserInfo\x12\x10\n\x08nickName\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"P\n\x0eUpdateUserInfo\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x62irthDay\x18\x04 \x01(\x04\"\x81\x01\n\x10UserInfoResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08nickName\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12\x10\n\x08\x62irthDay\x18\x05 \x01(\x04\x12\x0e\n\x06gender\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\x05\"B\n\x10UserListResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.UserInfoResponse2\xb7\x02\n\x04User\x12\x32\n\x0eGetUserByPhone\x12\r.PhoneRequest\x1a\x11.UserInfoResponse\x12+\n\x0bGetUserList\x12\t.PageInfo\x1a\x11.UserListResponse\x12\x30\n\x0bGetUserByID\x12\x0e.UserIDRequest\x1a\x11.UserInfoResponse\x12\x30\n\nCreateUser\x12\x0f.CreateUserInfo\x1a\x11.UserInfoResponse\x12\x35\n\nUpdateUser\x12\x0f.UpdateUserInfo\x1a\x16.google.protobuf.Empty\x12\x33\n\rCheckPassword\x12\x12.PasswordCheckInfo\x1a\x0e.CheckResponseB\tZ\x07.;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007.;proto'
  _globals['_PASSWORDCHECKINFO']._serialized_start=43
  _globals['_PASSWORDCHECKINFO']._serialized_end=107
  _globals['_PAGEINFO']._serialized_start=109
  _globals['_PAGEINFO']._serialized_end=146
  _globals['_CHECKRESPONSE']._serialized_start=148
  _globals['_CHECKRESPONSE']._serialized_end=180
  _globals['_PHONEREQUEST']._serialized_start=182
  _globals['_PHONEREQUEST']._serialized_end=211
  _globals['_USERIDREQUEST']._serialized_start=213
  _globals['_USERIDREQUEST']._serialized_end=240
  _globals['_CREATEUSERINFO']._serialized_start=242
  _globals['_CREATEUSERINFO']._serialized_end=309
  _globals['_UPDATEUSERINFO']._serialized_start=311
  _globals['_UPDATEUSERINFO']._serialized_end=391
  _globals['_USERINFORESPONSE']._serialized_start=394
  _globals['_USERINFORESPONSE']._serialized_end=523
  _globals['_USERLISTRESPONSE']._serialized_start=525
  _globals['_USERLISTRESPONSE']._serialized_end=591
  _globals['_USER']._serialized_start=594
  _globals['_USER']._serialized_end=905
# @@protoc_insertion_point(module_scope)
